;              
CREATE USER IF NOT EXISTS "" PASSWORD '' ADMIN;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B3F40914_8611_4FAE_A75F_FB11754B8FE6 START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DD13F5DB_FAC9_489E_99F2_4E300D8F2D5E START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_16FD5ADA_9EAA_4B25_96DA_1CF14E9FA222 START WITH 11 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6CCDBCB4_38D8_4812_A76F_D62578AACA0E START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9D682A77_CBA4_497C_897E_8950D2E8CF61 START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0C54DB96_5E22_4B19_A4EB_8FD4A63FFD6E START WITH 7 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1262B5BC_FA68_4E7D_8551_86C8AC4DF72C START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_603AF942_A6FF_4AC1_B795_2BF354ADC4D7 START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0459D10E_8BBF_4169_A717_03F32A798C71 START WITH 1 BELONGS_TO_TABLE;     
CREATE CACHED TABLE PUBLIC.ORGANISMS(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9D682A77_CBA4_497C_897E_8950D2E8CF61) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9D682A77_CBA4_497C_897E_8950D2E8CF61,
    NAME VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL
);     
ALTER TABLE PUBLIC.ORGANISMS ADD CONSTRAINT PUBLIC.CONSTRAINT_26 PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORGANISMS;
CREATE CACHED TABLE PUBLIC.NETWORKS(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1262B5BC_FA68_4E7D_8551_86C8AC4DF72C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1262B5BC_FA68_4E7D_8551_86C8AC4DF72C,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    ORGANISM_ID INTEGER NOT NULL,
    GROUP_ID INTEGER NOT NULL,
    DATA_FILE_ID INTEGER,
    FORMAT_ID INTEGER,
    PUBMED_ID BIGINT,
    SOURCE VARCHAR(255),
    USER VARCHAR(255),
    COMMENT VARCHAR(4000),
    IS_DEFAULT TINYINT,
    RESTRICTED_LICENSE TINYINT,
    ENABLED TINYINT DEFAULT FALSE NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    EXTRA VARCHAR(2048),
    TYPE VARCHAR(16) NOT NULL,
    ATTRIBUTE_METADATA_ID INTEGER
);    
ALTER TABLE PUBLIC.NETWORKS ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.NETWORKS; 
CREATE CACHED TABLE PUBLIC.GROUPS(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_16FD5ADA_9EAA_4B25_96DA_1CF14E9FA222) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_16FD5ADA_9EAA_4B25_96DA_1CF14E9FA222,
    NAME VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    GROUP_TYPE VARCHAR(16) NOT NULL
);   
ALTER TABLE PUBLIC.GROUPS ADD CONSTRAINT PUBLIC.CONSTRAINT_7DD PRIMARY KEY(ID);
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.GROUPS;  
INSERT INTO PUBLIC.GROUPS(ID, NAME, CODE, GROUP_TYPE) VALUES
(1, 'Co-expression', 'coexp', 'NETWORK'),
(2, 'Physical interactions', 'pi', 'NETWORK'),
(3, 'Genetic interactions', 'gi', 'NETWORK'),
(4, 'Co-localization', 'coloc', 'NETWORK'),
(5, 'Shared protein domains', 'spd', 'NETWORK'),
(6, 'Predicted', 'predict', 'NETWORK'),
(7, 'Pathway', 'path', 'NETWORK'),
(8, 'Other', 'other', 'NETWORK'),
(9, 'Attributes', 'attrib', 'ATTRIBUTE'),
(10, 'Functions', 'func', 'FUNCTION'); 
CREATE CACHED TABLE PUBLIC.FORMATS(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0C54DB96_5E22_4B19_A4EB_8FD4A63FFD6E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0C54DB96_5E22_4B19_A4EB_8FD4A63FFD6E,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(128)
);         
ALTER TABLE PUBLIC.FORMATS ADD CONSTRAINT PUBLIC.CONSTRAINT_26A PRIMARY KEY(ID);               
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.FORMATS;  
INSERT INTO PUBLIC.FORMATS(ID, NAME, DESCRIPTION) VALUES
(1, 'profile', 'real-valued profile, n-columns, Pearson correlation'),
(2, 'network', '2 or 3 columns, third column assumed 1 if not given'),
(3, 'direct to shared neighbour', '2 columns, log-freq dot-prod'),
(4, 'attributes to shared neighbour', 'variable length rows, log-req dot-prod'),
(5, 'attributes', 'variable length rows, loaded as a group of connected networks per attribute'),
(6, 'direct network - already normalized', 'direct network, already normalized'); 
CREATE CACHED TABLE PUBLIC.IDENTIFIERS(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_603AF942_A6FF_4AC1_B795_2BF354ADC4D7) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_603AF942_A6FF_4AC1_B795_2BF354ADC4D7,
    ORGANISM_ID INTEGER NOT NULL,
    DATA_FILE_ID INTEGER
);       
ALTER TABLE PUBLIC.IDENTIFIERS ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.IDENTIFIERS;              
CREATE CACHED TABLE PUBLIC.ATTRIBUTE_METADATA(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0459D10E_8BBF_4169_A717_03F32A798C71) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0459D10E_8BBF_4169_A717_03F32A798C71,
    DATA_FILE_ID INTEGER,
    LINKOUT_URL VARCHAR(255),
    LINKOUT_LABEL VARCHAR(255)
);    
ALTER TABLE PUBLIC.ATTRIBUTE_METADATA ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ATTRIBUTE_METADATA;       
CREATE CACHED TABLE PUBLIC.DATAFILES(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6CCDBCB4_38D8_4812_A76F_D62578AACA0E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6CCDBCB4_38D8_4812_A76F_D62578AACA0E,
    ORGANISM_ID INTEGER NOT NULL,
    FILENAME VARCHAR(128),
    ORIGINAL_FILENAME VARCHAR(128),
    FILE_TYPE VARCHAR(16),
    UPLOAD_DATE TIMESTAMP,
    STATUS VARCHAR(16),
    PROCESSING_DETAILS VARCHAR(4096)
);
ALTER TABLE PUBLIC.DATAFILES ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DATAFILES;
CREATE CACHED TABLE PUBLIC.FUNCTIONS(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B3F40914_8611_4FAE_A75F_FB11754B8FE6) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B3F40914_8611_4FAE_A75F_FB11754B8FE6,
    DATA_FILE_ID INTEGER,
    DESCRIPTION_FILE_ID INTEGER,
    FUNCTION_TYPE VARCHAR(16) NOT NULL,
    COMMENT VARCHAR(2048)
);       
ALTER TABLE PUBLIC.FUNCTIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_9D PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FUNCTIONS;
CREATE CACHED TABLE PUBLIC.DB_VERSION(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_DD13F5DB_FAC9_489E_99F2_4E300D8F2D5E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DD13F5DB_FAC9_489E_99F2_4E300D8F2D5E,
    VERSION_ID VARCHAR(255) NOT NULL
);              
ALTER TABLE PUBLIC.DB_VERSION ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DB_VERSION;               
ALTER TABLE PUBLIC.GROUPS ADD CONSTRAINT PUBLIC.CONSTRAINT_7D UNIQUE(CODE);    
ALTER TABLE PUBLIC.ORGANISMS ADD CONSTRAINT PUBLIC.CONSTRAINT_2 UNIQUE(CODE);  
